# Generated by Django 2.1.5 on 2019-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popmemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=120)),
                ('pop_img', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('freq', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
